# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is commited to
# your git repository.
cache:
  paths:
  - vendor/

before_script:
# Install composer dependencies
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install

tests:
  script:
  - vendor/bin/phpunit --configuration phpunit.xml  --coverage-text --colors=never